<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mental_health_data [
<!ELEMENT mental_health_data (record+)>
<!ELEMENT record (Age, Gender, Relationship_Status, Occupation, Organization, Social_Media_Usage, Social_Media_Platforms, Daily_Social_Media_Time, Frequency_Usage_No_Purpose, Frequency_Distracted, Restless_Without_Social_Media, Distractibility_Scale, Difficulty_Concentrating_Scale, Frequency_Depressed_Scale, Sleep_Issues_Scale)>

<!ELEMENT Age (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Relationship_Status (#PCDATA)>
<!ELEMENT Occupation (#PCDATA)>
<!ELEMENT Organization (#PCDATA)>
<!ELEMENT Social_Media_Usage (#PCDATA)>
<!ELEMENT Social_Media_Platforms (#PCDATA)>
<!ELEMENT Daily_Social_Media_Time (#PCDATA)>
<!ELEMENT Frequency_Usage_No_Purpose (#PCDATA)>
<!ELEMENT Frequency_Distracted (#PCDATA)>
<!ELEMENT Restless_Without_Social_Media (#PCDATA)>
<!ELEMENT Distractibility_Scale (#PCDATA)>
<!ELEMENT Difficulty_Concentrating_Scale (#PCDATA)>
<!ELEMENT Frequency_Depressed_Scale (#PCDATA)>
<!ELEMENT Sleep_Issues_Scale (#PCDATA)>
]>
<mental_health_data>
<record>
<Age>25</Age>
<Gender>Female </Gender>
<Relationship_Status>Single</Relationship_Status>
<Occupation>Student</Occupation>
<Organization>University</Organization>
<Social_Media_Usage>Yes</Social_Media_Usage>
<Social_Media_Platforms>Facebook, Instagram</Social_Media_Platforms>
<Daily_Social_Media_Time>Between 2 and 3 hours</Daily_Social_Media_Time>
<Frequency_Usage_No_Purpose>5</Frequency_Usage_No_Purpose>
<Frequency_Distracted>3</Frequency_Distracted>
<Restless_Without_Social_Media>2</Restless_Without_Social_Media>
<Distractibility_Scale>5</Distractibility_Scale>
<Difficulty_Concentrating_Scale>5</Difficulty_Concentrating_Scale>
<Frequency_Depressed_Scale>5</Frequency_Depressed_Scale>
<Sleep_Issues_Scale>5</Sleep_Issues_Scale>
</record>
<record>
<Age>21</Age>
<Gender>Male</Gender>
<Relationship_Status>In a relationship</Relationship_Status>
<Occupation>University Student</Occupation>
<Organization>University</Organization>
<Social_Media_Usage>Yes</Social_Media_Usage>
<Social_Media_Platforms>Facebook, Twitter, Instagram, YouTube, Discord, Reddit</Social_Media_Platforms>
<Daily_Social_Media_Time>Between 2 and 3 hours</Daily_Social_Media_Time>
<Frequency_Usage_No_Purpose>5</Frequency_Usage_No_Purpose>
<Frequency_Distracted>3 </Frequency_Distracted>
<Restless_Without_Social_Media>2</Restless_Without_Social_Media>
<Distractibility_Scale>5</Distractibility_Scale>
<Difficulty_Concentrating_Scale>5</Difficulty_Concentrating_Scale>
<Frequency_Depressed_Scale>5</Frequency_Depressed_Scale>
<Sleep_Issues_Scale> 5</Sleep_Issues_Scale>
</record>
<record>
<Age>21</Age>
<Gender>Female</Gender>
<Relationship_Status>Single</Relationship_Status>
<Occupation>Student</Occupation>
<Organization>University</Organization>
<Social_Media_Usage>Yes</Social_Media_Usage>
<Social_Media_Platforms>Facebook, Twitter, Instagram, YouTube, Discord, Reddit</Social_Media_Platforms>
<Daily_Social_Media_Time>More than 5 hours</Daily_Social_Media_Time>
<Frequency_Usage_No_Purpose>4</Frequency_Usage_No_Purpose>
<Frequency_Distracted>3</Frequency_Distracted>
<Restless_Without_Social_Media>2</Restless_Without_Social_Media>
<Distractibility_Scale>4</Distractibility_Scale>
<Difficulty_Concentrating_Scale>4</Difficulty_Concentrating_Scale>
<Frequency_Depressed_Scale>5</Frequency_Depressed_Scale>
<Sleep_Issues_Scale>5</Sleep_Issues_Scale>
</record>
<record>
<Age>22</Age>
<Gender>Female</Gender>
<Relationship_Status> Single</Relationship_Status>
<Occupation>University Student</Occupation>
<Organization>University</Organization>
<Social_Media_Usage>True</Social_Media_Usage>
<Social_Media_Platforms>Facebook, Twitter, Instagram, YouTube, Discord, Pinterest, TikTok</Social_Media_Platforms>
<Daily_Social_Media_Time>Between 2 and 3 hours</Daily_Social_Media_Time>
<Frequency_Usage_No_Purpose>4</Frequency_Usage_No_Purpose>
<Frequency_Distracted>4</Frequency_Distracted>
<Restless_Without_Social_Media>2</Restless_Without_Social_Media>
<Distractibility_Scale>3</Distractibility_Scale>
<Difficulty_Concentrating_Scale>3</Difficulty_Concentrating_Scale>
<Frequency_Depressed_Scale>3</Frequency_Depressed_Scale>
<Sleep_Issues_Scale>4</Sleep_Issues_Scale>
</record>
<record>
<Age>20 </Age>
<Gender>Male</Gender>
<Relationship_Status>Single</Relationship_Status>
<Occupation>University Student</Occupation>
<Organization>University</Organization>
<Social_Media_Usage>0</Social_Media_Usage>
<Social_Media_Platforms>Reddit, Pinterest</Social_Media_Platforms>
<Daily_Social_Media_Time>Less than an Hour</Daily_Social_Media_Time>
<Frequency_Usage_No_Purpose>1</Frequency_Usage_No_Purpose>
<Frequency_Distracted>1</Frequency_Distracted>
<Restless_Without_Social_Media>1</Restless_Without_Social_Media>
<Distractibility_Scale>1</Distractibility_Scale>
<Difficulty_Concentrating_Scale>1</Difficulty_Concentrating_Scale>
<Frequency_Depressed_Scale>1</Frequency_Depressed_Scale>
<Sleep_Issues_Scale>1</Sleep_Issues_Scale>
</record>
</mental_health_data>
